language: go
go:
  - 1.4.3
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip
install:
  - go get ./...
  - '[ "$TRAVIS_GO_VERSION" != 1.4.3 ] || go get golang.org/x/tools/cmd/cover'
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=count ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
