language: go
go:
  - 1.4.3
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=count ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
